### ISSUE TITLE
[DOC] `rapids_cpm_find` docs should explicitly state it supports arbitrary projects

### ISSUE THREAD

**Issue by allisonvacanti** [rapidsai/rapids-cmake#100]
## Report needed documentation

Reference: https://docs.rapids.ai/api/rapids-cmake/nightly/command/rapids_cpm_find.html

**Report needed documentation**

It's not clear what the supported projects/versions are when looking for help on this function.

**Describe the documentation you'd like**

Link to (or list) the supported packages / versions from this function's documentation page.

**Steps taken to search for needed documentation**

This is available elsewhere in the docs, but it would be convenient to have it available from `rapids_cpm_find`.

**Comment by robertmaynard** [comment]
`rapids_cpm_find` supports using with any arbitrary project that rapids-cmake doesn't have a function for.

Or are you asking for formal documentation on what version of thrust, rmm, gtest, that will be used?
