### ISSUE TITLE
[FEA] provide `rapids_cpm_fmt`

### ISSUE THREAD

**Issue by alliepiper** [rapidsai/rapids-cmake#101]
**Is your feature request related to a problem? Please describe.**

We'd like to use rapids-cmake for all dependency management in NVBench, and the `fmt` library is one of our dependencies.

**Describe the solution you'd like**

Support for `rapids_cpm_fmt` that does the equivalent of

```
CPMAddPackage(
  NAME fmt
  GITHUB_REPOSITORY fmtlib/fmt
  GIT_TAG 7.1.3
)
```

**Describe alternatives you've considered**

We could manage this dependency manually, but would like to make use of the extra functionality in `rapids-cpm` for consistency.

**Comment by bdice** [comment]
@allisonvacanti FYI, we added `rapids_cpm_fmt` in #364 because we need it to pull the header-only `fmt` in alongside a more recent version of `spdlog` which will be updated soon (not yet complete). Just wanted to close the loop here because the requested functionality now exists.
