### ISSUE TITLE
[FEA] Add `rapids_cpm_nlohmann_json`

### ISSUE THREAD

**Issue by allisonvacanti** [rapidsai/rapids-cmake#102]
**Is your feature request related to a problem? Please describe.**

We'd like to use rapids-cmake for all dependency management in NVBench, and the `nlohmann_json` library is one of our dependencies.

**Describe the solution you'd like**

Support for `rapids_cpm_nlohmann_json` that does the equivalent of

```
CPMAddPackage(
  NAME nlohmann_json
  # Latest release headers:
  VERSION 3.9.1
  URL https://github.com/nlohmann/json/releases/download/v3.9.1/include.zip
  URL_HASH SHA256=6bea5877b1541d353bd77bdfbdb2696333ae5ed8f9e8cc22df657192218cad91
  PATCH_COMMAND
    # Work around compiler bug in nvcc 11.0, see NVIDIA/NVBench#18
    ${CMAKE_COMMAND} -E copy
      "${CMAKE_CURRENT_SOURCE_DIR}/cmake/patches/nlohmann_json.hpp"
      "./include/nlohmann/json.hpp"
)
```

**Describe alternatives you've considered**

We could manage this dependency manually, but would like to make use of the extra functionality in `rapids-cpm` for consistency. This particular dependency is tricky to fetch because the usual "clone from github" approach is extremely slow, and the sources require patching to support nvcc 11.0.

**Comment by robertmaynard** [comment]
You can do this via the `rapids_cpm_find` as it supports all CPM args including PATCH_COMMAND
