### ISSUE TITLE
[FEA] Support all CTK-supported SM arches in `cuda_init_architectures`

### ISSUE THREAD

**Issue by allisonvacanti** [rapidsai/rapids-cmake#104]
**Is your feature request related to a problem? Please describe.**

Thrust supports all architectures supported by CTK, including deprecated ones. This means we currently need to build against SM35+ in our benchmarking library.

However, `rapids_cuda_init_architectures` only adds architectures supported by RAPIDS (sm60+) when `CMAKE_CUDA_ARCHITECTURES=ALL`.

**Describe the solution you'd like**

Ideally, these special values would be something like:
- `ALL`: non deprecated arches supported by CTK (e.g. sm53+)
- `ALL_LEGACY`: all arches supported by CTK, including deprecated (e.g. sm35+)
- `RAPIDS`: all arches supported by RAPIDS (e.g. sm60+)

Since the current convention around `ALL` is already in use by rapids-cmake users, maybe the following values would be more agreeable and less disruptive:
- `CTK`: non deprecated arches supported by CTK (e.g. sm53+)
- `CTK_LEGACY`: all arches supported by CTK, including deprecated (e.g. sm35+)
- `ALL` / `RAPIDS`: all arches supported by RAPIDS (e.g. sm60+)

Also -- I'm not sure if `NATIVE` will add <sm60 if such a card is present. If not, adding `NATIVE_CTK` + `NATIVE_CTK_LEGACY` (or similar) would be useful for us.

**Describe alternatives you've considered**

We can still just list all arches explicitly, so this is a low-priority issue with an easy workaround. Most users will want `NATIVE` anyway.

**Comment by robertmaynard** [comment]
Closing this issue as https://github.com/rapidsai/rapids-cmake/issues/314 better represents what rapids-cmake will do. 

If you need to build with against all support archs, using the new `CMAKE_CUDA_ARCHITECTURES=all/all-major` is the best approach.
