### ISSUE TITLE
[FEA] Update libcudacxx version from 1.6 to 1.7

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/rapids-cmake#139]
**Is your feature request related to a problem? Please describe.**
https://github.com/NVIDIA/cuCollections added stream support but the most recent version of cuCollection requires libcudacxx 1.7.

**Describe the solution you'd like**
Update libcudacxx version from 1.6 to 1.7

**Comment by robertmaynard** [comment]
Do we have a timeline for 1.7 to move out of early access?

**Comment by seunghwak** [comment]
I am not aware of the 1.7 release date (I just realized that 1.7 hasn't been released, yet). So, I expect this issue to be addressed after official 1.7 release.

**Comment by robertmaynard** [comment]
libcudacxx 1.7.0 has now been released, the linked PR has been updated to use it
