### ISSUE TITLE
[DOC] Link Sphinx `ref`s to official CMake Docs

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/rapids-cmake#141]
I've been reading through the `rapids-cmake` docs and I noticed that we use Sphinx [refs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role) in places like [here](https://github.com/rapidsai/rapids-cmake/blob/e430e4cf08062d312c434497e31bb4ed8dad61d5/rapids-cmake/cmake/support_conda_env.cmake#L39). I think the objective of the `ref` is to link to the official, external CMake docs, but it doesn't seem to be working currently. I think we need to configure our [intersphinx_mapping variable](https://github.com/rapidsai/rapids-cmake/blob/e430e4cf08062d312c434497e31bb4ed8dad61d5/docs/conf.py#L121) to [something like this](https://gitlab.kitware.com/cmake/cmake/-/issues/21610#note_875068) in order for the external links to work correctly.

Here's the official docs on the `intersphinx_mapping` variable for reference: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping

I can try to tackle this after the holidays if no one gets to it before then.

**Comment by robertmaynard** [comment]
That would be awesome if you could get that working
