### ISSUE TITLE
[BUG] Conda recipes that have separate `build` and `host` sections don't find packages correctly using `rapids_cmake_support_conda_env`

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/rapids-cmake#179]
**Describe the bug**

Conda recipes use the `requirements` section to define build time and runtime dependencies of a project. WIthin the `requirements` sections, there's three subsections `build`, `host`, and `run`. `build` is supposed to contain native tools used for building like `cmake`, `make`, `ninja`, compilers, etc. `host` contains libraries for the target platform of the project (for example to allow cross compiling) typically used for linking. Read more here: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#requirements-section

It isn't well documented and is likely legacy, but there's also the possibility of running with only two sections a `build` and `run` section, in which the build tools and target platform library dependencies are merged into a single section. Most of the RAPIDS conda recipes are defined in this way, likely due to legacy reasons.

The `build` and `host` sections map to different conda environments during a conda build and have environment variables of `BUILD_PREFIX` and `PREFIX` set accordingly. Where there's only a `build` section in the recipe there can still be a corresponding `PREFIX` environment created alongside the `BUILD_PREFIX` environment depending on the packages included in the `build` sections. Notably using the `{{ compiler(...) }}` jinja templates causes two separate environments to be created.

It looks like if you have a recipe that uses both the `build` and `host` sections as expected, then we end up improperly setting the search paths to find packages in the `build` environment as opposed to the `host` environment: https://github.com/rapidsai/rapids-cmake/blob/branch-22.06/rapids-cmake/cmake/support_conda_env.cmake#L78-L83. This causes issues when building a project that depends on something that CMake or other build tools also depend on, i.e. `libcurl`.

In general, we should probably make searching in the `build` environment opt-in as opposed to default behavior because it can cause issues in cross compiling, but I understand some rapids conda recipes are defined using only `build` and `run` as of now. An easy temporary fix for these recipes would be to just change the `build` section to `host` for now.

**Expected behavior**

When using `rapids_cmake_support_conda_env` I expect the packages defined in the `host` section of my conda recipe to be found before finding packages in the `build` environment.

cc @jakirkham because conda recipes 😄

**Comment by robertmaynard** [comment]
Am I correct in understanding that if we re-order `PREFIX` to be before `BUILD_PREFIX` we would find `host` packages before `build`  and resolve this issue?

I don't think we can eliminate `BUILD_PREFIX` entirely as projects that do something like `find_package(Git)` would expect to be able to find the local machine `Git` package.

**Comment by kkraus14** [comment]
@robertmaynard I believe so. The only issue that comes to my mind is if something like `Python` is needed both for a local executable and as a library to link against then I believe we'll end up with the wrong executable as we'll get the one we intend to use for cross compiling. This could be avoided by not using something like the `Python3_EXECUTABLE` result variable.

I'm not sure what best practices are for cross compiling with CMake where it may be that I'm creating a problem in my head based on usage patterns that aren't correct 😄.

**Comment by robertmaynard** [comment]
This helps explain what a 'proper' CMake based cross-compilation process would involve. https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#running-executables-built-in-the-project

But in short, if a host based python execution was needed, we would have to store those results, and replay them when cross-compiling.

**Comment by kkraus14** [comment]
Okay, sounds like just swapping the `build` and `host` prefixes should generally fix things then. I'll throw up a PR.

**Comment by jakirkham** [comment]
This is also how [Conda-Build does things]( https://github.com/conda/conda-build/blob/0a6efdcfa02484954e7a3fdf5c2ec4bb3cb6682e/conda_build/render.py#L669-L670 ). Namely `host` having higher priority than `build`.

**Comment by jakirkham** [comment]
Actually I think I was wrong before. Did more digging here and it seems `build` comes first in `PATH`.

Conda-Build writes a file called `build_env_setup.sh` (or `build_env_setup.bat` on Windows). This can be inspected in any local Conda-Build run. Here's the [code modifying the `PATH`]( https://github.com/conda/conda-build/blob/400fde1da22f8665b1dddc1286a4c21a5f5cd45a/conda_build/build.py#L2589-L2591 ). This is consistent with how [activation is handled]( https://github.com/conda/conda-build/blob/400fde1da22f8665b1dddc1286a4c21a5f5cd45a/conda_build/build.py#L1851-L1868 ) later.

Not sure why `conda render` and `conda build` handle these differently.
