### ISSUE TITLE
[BUG] `rapids_export` Does Not Work if the Variable `RAPIDS_VERSION` Exists

### ISSUE THREAD

**Issue by mdemoret-nv** [rapidsai/rapids-cmake#200]
**Describe the bug**
If you have the cache variable `RAPIDS_VERSION` set before calling `rapids_export()`, the version it chooses can be incorrect if you omit the `VERSION` argument or set `VERSION` with no value. In these situations, the documentation states it will default to use `PROJECT_VERSION`. Instead it simply uses the value in `RAPIDS_VERSION`.

We ran into this in SRF and needed to explicitly set the version to get around the bug (here is the PR with the workaround: https://github.com/nv-morpheus/SRF/pull/30). In SRF, we use the cache variable `RAPIDS_VERSION` to indicate which version of RMM, RAPIDS CMake, etc. we are using to build with. It took a while to discover why the generated `srf-config-version.cmake` was using the incorrect version value.

**Steps/Code to reproduce bug**
The following pseudocode should reproduce the bug:

```cmake
project(my_project
  VERSION 22.06.00
  LANGUAGES C CXX
)

# Need to set the RAPIDS_VERSION cache variable
set(RAPIDS_VERSION "21.10" CACHE STRING "RAPIDS Libraries Version")

# This will create a version file with 21.10 as the version, not 22.06
rapids_export(INSTALL ${PROJECT_NAME}
  EXPORT_SET ${PROJECT_NAME}-core-exports
  GLOBAL_TARGETS libmy_project
  VERSION
  NAMESPACE my_project::
)
```
Also ommitting the `VERSION` argument will hit the bug as well.

**Expected behavior**
As indicated by the documentation, when `VERSION` has no value or is ommitted as an argument, `rapids_export` should default to using `PROJECT_VERSION`.

**Environment details (please complete the following information):**
 - CMake version 3.22

**Additional context**
This issue can be quickly fixed by changing the prefix used for `cmake_parse_arguments`. Currently the code uses `cmake_parse_arguments(RAPIDS ...)` which creates too common of variable names like `RAPIDS_VERSION`, `RAPIDS_NAMESPACE`, `RAPIDS_DOCUMENTATION`, etc. Instead the prefix should be something like `_RAPIDS` to prevent collisions.

**Comment by robertmaynard** [comment]
Couple of notes:

> set VERSION with no value.
This is unsupported. As noted in the docs ``[VERSION <X.Y.Z>]`` if you provide the `VERSION` keyword a value must also be provided. It can be `OFF` or explicit numeric version value.

I am open to any changes to the API docs to make this more clear.

> This issue can be quickly fixed by changing the prefix used for cmake_parse_arguments. Currently the code uses cmake_parse_arguments(RAPIDS ...) which creates too common of variable names like RAPIDS_VERSION, RAPIDS_NAMESPACE, RAPIDS_DOCUMENTATION, etc. Instead the prefix should be something like _RAPIDS to prevent collisions.

I think this is the correct solution, and will need to be applied project wide so we don't run into this issue with other commands.
