### ISSUE TITLE
[BUG] CMAKE_CUDA_ARCHITECTURES=NATIVE conflicts with CMake 3.24.0-rc3 `native`

### ISSUE THREAD

**Issue by robertmaynard** [rapidsai/rapids-cmake#217]
**Describe the bug**

Using `CMAKE_CUDA_ARCHITECTURES=NATIVE` was accepted as an argument and working (maybe unintentionally) in CMake 3.22.x.

It is widely used in many CUDA libraries, e.g.  
https://github.com/rapidsai/cudf/blob/branch-22.08/build.sh#L262

When trying with _CMake 3.24.0-rc3_, it has to be replaced by `CMAKE_CUDA_ARCHITECTURES=native` (i.e lowercase value) else it's failing with:
```
CMake Error at /some/local/install/share/cmake-3.24/Modules/CMakeDetermineCUDACompiler.cmake:279 (message):
  CMAKE_CUDA_ARCHITECTURES:
    NATIVE
  is not one of the following:
    * a semicolon-separated list of integers, each optionally
      followed by '-real' or '-virtual'
    * a special value: all, all-major, native
```

I suspect the new _case sensitivity_ is related to the new regular expression in:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7202/diffs#b2fb7bf5b0acdc13be102e624ffe8eb2175fd813_325_278

Is this intentional ? a regression ?  
At least several official CUDA libraries no longer compile in some setups with `3.24.0-rc3`

**Additional context**
Originally reported at https://gitlab.kitware.com/cmake/cmake/-/issues/23739

**Comment by vpalatin** [comment]
Thanks for the details you put in the [original cmake issue ](https://gitlab.kitware.com/cmake/cmake/-/issues/23739).

The failure was actually escaping rapids-cmake, seems to work fine with it so far, I found the mistake thanks to your hint.

We can probably close this bug with PEBCAK.

**Comment by robertmaynard** [comment]
Happy to hear you tracked down the issue.
