### ISSUE TITLE
[FEA] Update nvcomp version to 2.3.3

### ISSUE THREAD

**Issue by jbrennan333** [rapidsai/rapids-cmake#219]
Currently cuDF is pulling in nvcomp release 2.3.2. The DevTech team is in the process of releasing 2.3.3.

Once it is available, we should consider moving to it for release 22.08.
This version includes fixes for deflate:
```Fixed the issue of missing nvcompBatchedDeflateDecompressGetTempSizeEx.
Fixed the correctness issue of deflate compression.
Update the nvcompBatchedDeflateGetDecompressSizeAsync.
Add API tests for deflate, and change the file structure of deflate (Add template parameters)
```

Note that for cuDF, we worked around the problem with the missing `nvcompBatchedDeflateDecompressGetTempSizeEx` in PR: https://github.com/rapidsai/cudf/pull/11213

**Comment by robertmaynard** [comment]
I believe moving to 2.3.3 will also allow us to remove the work around of https://github.com/rapidsai/rapids-cmake/pull/218

**Comment by vyasr** [comment]
While I am supportive of this, I'm a little wary of trying to squeeze this in to 22.08. For my edification, how severe is the deflate issue? How critical is the `nvcompBatchedDeflateGetDecompressSizeAsync` API for Spark?

We can evaluate based on when the binaries are officially released. Given the headaches that have ensued from the last couple nvcomp updates and the fact that some members of the team will likely be dealing with last minute build issues related to other pushes like Hopper compatibility, I'm just a little worried about trying to update nvcomp after burn down starts

**Comment by jbrennan333** [comment]
The deflate issue sounds pretty serious: 

From Nvcomp team description: Fixed an issue in Deflate compression that led to incorrect results if the user didn’t zero the compressed buffer before calling compression.

I don't see any references to `nvcompBatchedDeflateGetDecompressSizeAsync` in cuDF, so we don't use it in Spark.

**Comment by jbrennan333** [comment]
Note that ZLIB is still experimental in cuDF 22.08 - you have to opt in by setting `LIBCUDF_NVCOMP_POLICY=ALWAYS`.

**Comment by jbrennan333** [comment]
NVCOMP-2.3.3 is live on the download page:
`https://developer.download.nvidia.com/compute/nvcomp/2.3.3/local_installers/nvcomp_install_CUDA_11.x.tgz
`

I will download and verify with spark.

**Comment by jbrennan333** [comment]
I have verified nvcomp-2.3.3 by building libcudf/spark-rapids-jni/spark-rapids with it. I ran the spark-rapids integration tests for orc/parquet compression.   I ran the nds2.0 power run at scale 100GB on my RTX 4000 desktop with parquet/zstd and orc/zstd and verified that the results matched the cpu output.   I also built cudf-python and verified I could load cudf (to verify the missing api problem).

**Comment by jbrennan333** [comment]
@robertmaynard, @vyasr, @vuule, @devavret we should decide soon if we are going to pull this in for 22.08.

**Comment by vyasr** [comment]
I've created https://github.com/rapidsai/rapids-cmake/pull/221 to update and https://github.com/rapidsai/cudf/pull/11327 to test it. Once we can confirm that tests all pass in CI we can make a final call on whether or not this makes it into 22.08, but assuming that the tests pass I think it's probably OK.

**Comment by vyasr** [comment]
Looks like tests are passing on the cudf PR, so I'm not opposed to moving forward with this depending on how @vuule and @robertmaynard feel.

**Comment by vuule** [comment]
The deflate issue does impact us, as our compression output buffer is not initialized. On the other hand, deflate support is experimental in 22.08.
I'm slightly inclined to move this to 22.10, as we anyway don't get the full benefit unless we make further code changes to avoid the temp size workaround with 2.3.3.

**Comment by jbrennan333** [comment]
I defer to @vuule and @robertmaynard on this.  From a spark perspective, we are ok with 2.3.2 for 22.08, so deferring this to 22.10 is ok.

**Comment by robertmaynard** [comment]
I lean pushing 2.3.3 for 22.10 to minimize risk as we enter burndown.

**Comment by vyasr** [comment]
As long as Spark is not pushing hard for 22.08 I lean that way as well just for safety.
