### ISSUE TITLE
[BUG] Problems with default recipe and dependent projects using RAPIDS.cmake

### ISSUE THREAD

**Issue by hahnjo** [rapidsai/rapids-cmake#240]
**Describe the bug**
If a dependent project also uses `RAPIDS.cmake`, the default recipe will download and overwrite the file in the root build directory. This is especially problematic if the dependent project downloads an *older* version of `rapids-cmake`, pulling in an older `versions.json`.

**Steps/Code to reproduce bug**
Configure and build https://github.com/NVIDIA/cuCollections; it should work. Then re-run `cmake .` and observe that older versions of `libcudacxx` and `Thrust` are added (based on what https://github.com/NVIDIA/nvbench pulls in). The build will fail afterwards because cuCollections requires the newer versions.

**Expected behavior**
The build should be stable and work after reconfiguration.

**Comment by hahnjo** [comment]
One possibility would be to download `RAPIDS.cmake` (and everything else pulled in from there) into `CMAKE_CURRENT_BINARY_DIR`, but I don't know how that works out with building the dependencies and potentially having the same dependent project used transitively by multiple intermediate projects...

**Comment by robertmaynard** [comment]
This isn't an issue with rapids-cmake. It is a bug in the cuCollections CMakeLists.txt.

In the root CMakeLists.txt cuCollections has:
```cmake
if(NOT EXISTS ${CMAKE_BINARY_DIR}/RAPIDS.cmake)
  file(DOWNLOAD https://raw.githubusercontent.com/rapidsai/rapids-cmake/branch-22.08/RAPIDS.cmake
       ${CMAKE_BINARY_DIR}/RAPIDS.cmake)
endif()
include(${CMAKE_BINARY_DIR}/RAPIDS.cmake)
```

This guard around the file download causes the nvbench version of the RAPIDS.cmake to be the one that 'sticks' around. Instead you should always download the file so that when you reconfigure you have the cuCollection version.

**Comment by hahnjo** [comment]
> This guard around the file download causes the nvbench version of the RAPIDS.cmake to be the one that 'sticks' around. Instead you should always download the file so that when you reconfigure you have the cuCollection version.

And then the dependency again downloads its version of `RAPIDS.cmake` - not very nice overall...

**Comment by robertmaynard** [comment]
You can version the download if you so wish( download it to RAPIDS_22.08 ) which would also solve the issue.

I will update the rapids-cmake docs/examples to use `CMAKE_CURRENT_BINARY_DIR`. I didn't think this was a short term solution as it requires an update to nvbench to correct cuCollections.

**Comment by robertmaynard** [comment]
https://github.com/rapidsai/rapids-cmake/pull/241 updates the docs / examples to show best practices so the downloaded file doesn't get clobbered.
