### ISSUE TITLE
[BUG] CMake unable to use nvCOMP with version 2.4+

### ISSUE THREAD

**Issue by vuule** [rapidsai/rapids-cmake#246]
Unable to use newer version of nvCOMP when building cuDF as such:
`~/cudf/build.sh libcudf --cmake-args=\"-DCMAKE_PREFIX_PATH=~/nvcomp-dir -DCUDF_USE_PROPRIETARY_NVCOMP=OFF\"`
The build instead uses 2.3.3 version.

**Comment by robertmaynard** [comment]
@vuule Are you happy with the current setup and this can be closed?

**Comment by vuule** [comment]
Works fine now, thanks. Closing.
