### ISSUE TITLE
[QST] how to use conda_env

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/rapids-cmake#252]
**What is your question?**
Hi there, I read below "rapids_cmake_support_conda_env" from cudf CMakelist.txt
 
```
# * conda environment -----------------------------------------------------------------------------
rapids_cmake_support_conda_env(conda_env MODIFY_PREFIX_PATH)
```

May I ask what is it and how to use it?

Thx

**Comment by robertmaynard** [comment]
You can find the documentation on what the function does at: https://docs.rapids.ai/api/rapids-cmake/nightly/command/rapids_cmake_support_conda_env.html

In short it ensures that the project will search the conda lib/include directories
