### ISSUE TITLE
[QST] How to install older versions of rapids?

### ISSUE THREAD

**Issue by mahidhar96** [rapidsai/rapids-cmake#278]
**I'm trying to install an older version of rapids, 0.9 specifically. How do I do it?**
I couldn't find any branches of the older versions.
Is there a way to build a conda environment with the older versions?

Thanks in advance.

**Comment by vyasr** [comment]
Which rapids projects are you interested in using? cudf, cuml, ...? rapids-cmake is part of the build system and is probably not the package that you're interested in, so you will have more luck posting your query in the appropriate repo. That said, @beckernick or @taureandyernv might be more able to help you here.
