### ISSUE TITLE
Update minimum required CMake version to 3.24

### ISSUE THREAD

**Issue by robertmaynard** [rapidsai/rapids-cmake#315]
Updating CMake required version to 3.24 would offer us the following features:

- support for `native` keyword with `CMAKE_CUDA_ARCHITECTURES`
- support for `find_package` dependency providers. This would improve how projects could use `rapids_cpm_*` modules as we could directly hook into any `find_package` call.
- Better support for FindPython, particularly around its NumPy features that will allow us to reduce our dependency on scikit-build's CMake modules.

If we update directly to 3.25, we will also get
- Better support for nvtx via FindCUDAToolkit

**Comment by vyasr** [comment]
@robertmaynard can we close this? We've bumped all of RAPIDS to the newer version of CMake. What remains that I'm aware of is to modify the CMakeLists.txt here (and possibly all the tests as well). Is there anything else?

**Comment by robertmaynard** [comment]
There is some general improvements to rapids-cmake we can leverage with CMake 3.24+ but we can close this Issue and open those ideas as features
