### ISSUE TITLE
[BUG] All templates should contain the current year in the copyright

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rapids-cmake#325]
**Describe the bug**
rapids-cmake has multiple functions that generate CMake files such as Find*.cmake or *-config.cmake files. These templates all currently have the year hardcoded, resulting in the produced files being out of date.

**Steps/Code to reproduce bug**
The error is visible in every template file that contains a copyright header, [here is one example](https://github.com/rapidsai/rapids-cmake/blob/branch-23.02/rapids-cmake/find/template/find_module.cmake.in#L2).

**Expected behavior**
The copyright year should be written at build time when the file is being generated.

**Additional context**
I am happy to submit a patch but I am not sure what the best approach is. AFAICT there is no built-in way to accomplish this in CMake, so most likely we will need to use `execute_process` to run shell commands to get the values unless there is a better alternative.

**Comment by robertmaynard** [comment]
I am happy to review a patch to correct this issue :)

The best approach is to use `string(TIMESTAMP` to get the current year.

So something like:
```cmake
string(TIMESTAMP current_year [[%Y]] UTC)
configure_file(.... @ONLY)
```
And the template file would have:
```
Copyright (c) @current_year@, NVIDIA CORPORATION.
```
