### ISSUE TITLE
[BUG] detect_architectures.cmake hangs on 4080 and 1080 system

### ISSUE THREAD

**Issue by enp1s0** [rapidsai/rapids-cmake#411]
**Describe the bug**
While building RAPIDS Raft on a computer with two GPUs of different generations, 4080 and 1080, the detect_architectures.cmake script appears to hang. This is caused by the `cudaGetDeviceCount` function in `eval_gpu_archs.cu` not returning, and the script gets stuck at this point.

The detail of the computer is as follows:
- OS: Rocky Linux 9.1 (5.14.0-162.6.1.el9_1.0.1.x86_64)
- NVIDIA Driver: 530.41.03
- CUDA: cuda_12.1.r12.1/compiler.32688072_0
- GPU: 
   - GeForce RTX 4080
   - GeForce RTX 1080

I could avoid hanging by adding a compiler option `-gencode arch=compute_**,code=sm_**`.
`**` is OK for any compute capability.

While I don't believe that this is a bug of rapids-cmake, if someone knows the cause of this or has some comments to avoid this, it would be helpful to know. If adding the compiler option to detect_architectures.cmake is appropriate, I will create a pull request for that.

PR suggestion:

https://github.com/rapidsai/rapids-cmake/blob/55d6c4a947ed7d37892db7d8ce9a9e2b6249b965/rapids-cmake/cuda/detail/detect_architectures.cmake#L67-68
```cmake
    execute_process(COMMAND ${CMAKE_CUDA_COMPILER} -std=c++11 -o "${eval_exe}" "${eval_file}"
                    ERROR_FILE "${error_file}")
```

to

```cmake
    execute_process(COMMAND ${CMAKE_CUDA_COMPILER} -std=c++11 -gencode arch=compute_60,code=sm_60 -o "${eval_exe}" "${eval_file}"
                    ERROR_FILE "${error_file}")
```

**Comment by robertmaynard** [comment]
Interesting!

The `eval_gpu_archs.cu` file only contains cuda host calls and no CUDA kernels.  So I am surprised that a hang occurs. It does seem to be hanging on the first call to the cuda runtime so maybe it is trying to JIT some implicit kernels.

If you add `-gencode arch=compute_50,code=sm_50` instead of the `sm_60` version do you see correct execution?

**Comment by enp1s0** [comment]
I see, thank you for your explanation.
I will create a PR as you have described!

**Comment by enp1s0** [comment]
I have discovered that this problem does not occur when using different M/B and CPUs with the GPUs. Therefore, I will investigate further to determine the underlying cause of the problem. If necessary, I will reopen the issue. Thank you for your assistance.

Memo:
Problem occurrence:

- Intel Xeon E-2136 + ASUS WS C246 PRO: Issue observed
- AMD Ryzen 7 5800X + MSI MEG X570 UNIFY: No issue observed
