### ISSUE TITLE
[FEA] Implement a function to link a target appropriately to the CUDA runtime

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rapids-cmake#427]
**Is your feature request related to a problem? Please describe.**
rapids-cmake offers `rapids_cuda_init_runtime`, which implicitly changes the (default) CUDA linking behavior for all subsequent targets. This implicit behavior makes it difficult for consumers to reason about the CUDA linking behavior of targets since the resulting code is order-dependent and may be overridden by settings on particular targets.

**Describe the solution you'd like**
We should consider implementing a new function that accepts a target and adds a linkage to the appropriate CUDA library (dynamic or static) based on a function parameter. We could implement this either via a direct `target_link_libraries` call under the hood, or by creating a helper target (e.g. `add_library(rapids_cmake_cuda_lib...)`) that encodes the linkage, similar to how we handle conda in `rapids_cmake_conda_env`. If we wanted to incorporate math libraries we could include those as well, but we need to ensure that those are not constrained to the same type as the CUDA runtime (since the most common long-term behavior we want to encourage is statically linking cudart but dynamically linking the math libraries). We may instead benefit more from creating a separate function to handle the math library linkage.

**Comment by robertmaynard** [comment]
This does open the question if we also need to offer controls over the usage behavior of the linking.

So do we actually need
```cmake
add_library(uses_cuda SHARED <.....>)

rapids_cuda_set_runtime(uses_cuda PUBLIC USE_STATIC_RUNTIME ${PROJ_CUDA_STATIC_RUNTIME})
```
