### ISSUE TITLE
[FEA] Allow `rapids_test` to be used without CUDAToolkit

### ISSUE THREAD

**Issue by Jacobfaib** [rapidsai/rapids-cmake#478]
**Is your feature request related to a problem? Please describe.**

`rapids_test_init()` calls `find_package(CUDAToolKit REQUIRED)` if it does not find a `generate_resource_spec` executable at exactly `<build-dir>/rapids-cmake/generate_resource_spec`

Obviously this doesn't work so well on cpu-only builds.

**Describe the solution you'd like**

Provide a way of disabling this check, or provide an option `USE_GPU OFF`. Ideally we could simply do
```cmake
include(path/to/rapids-test.cmake)

rapids_test_init(ENABLE_GPU OFF)
```

**Describe alternatives you've considered**

Currently, we work around this by spoofing the file like so
```cmake
include(${rapids-cmake-dir}/test/detail/default_names.cmake)

set(patch_file "${CMAKE_CURRENT_SOURCE_DIR}/cmake/patches/generate_resource_spec.diff")
set(eval_file ${rapids-cmake-dir}/test/detail/generate_resource_spec.cpp)
set(eval_exe ${CMAKE_CURRENT_BINARY_DIR}/rapids-cmake/${rapids_test_generate_exe_name})

message("-- Patching ${eval_file}")
find_program(PATCH NAMES patch REQUIRED)
execute_process(
  COMMAND ${PATCH} --unified ${eval_file} --input=${patch_file} --ignore-whitespace --quiet
  TIMEOUT 15
  COMMAND_ERROR_IS_FATAL ANY
)

# Compile the (now patched) resource spec generator, and place the result where rapids
# expects to find it. try_compile() is a bit of a misnomer here -- this compilation MUST
# succeed, as rapids_test_init() below will fail if it doesn't
try_compile(
  SUCCEEDED
  SOURCES ${eval_file}
  COPY_FILE ${eval_exe}
  OUTPUT_VARIABLE compile_ret
)

if(NOT SUCCEEDED)
  message(FATAL_ERROR "Failed to compile patched resource spec generator for rapids_cmake_test(): ${compile_ret}" )
endif()
```
where `generate_resource_spec.diff` is
```diff
--- ./generate_resource_spec.cpp
+++ ./generate_resource_spec.cpp
@@ -14,7 +14,6 @@
  * limitations under the License.
  */

-#include <cuda_runtime_api.h>

 #include <iostream>
 #include <string>
@@ -27,7 +26,6 @@

 struct gpu {
   gpu(int i) : id{i} {};
-  gpu(int i, const cudaDeviceProp& prop) : id{i}, memory{prop.totalGlobalMem}, slots{100} {}
   int id        = 0;
   size_t memory = 0;
   int slots     = 0;
@@ -47,17 +45,8 @@
 int main()
 {
   std::vector<gpu> gpus;
-  int nDevices = 0;
-  cudaGetDeviceCount(&nDevices);
-  if (nDevices == 0) {
-    gpus.emplace_back(0);
-  } else {
-    for (int i = 0; i < nDevices; ++i) {
-      cudaDeviceProp prop;
-      cudaGetDeviceProperties(&prop, i);
-      gpus.emplace_back(i, prop);
-    }
-  }
+
+  gpus.emplace_back(0);

   version v{1, 0};
   std::cout << "{\n";
```

**Comment by robertmaynard** [comment]
The entire purpose of `rapids_test_init` ( https://docs.rapids.ai/api/rapids-cmake/stable/command/rapids_test_init/ ) and related commands is GPU resource management for tests. For this to work we want the CUDA toolkit installed ( no need for actual gpu ).

What functionality of `rapids_test` are you looking for that isn't provided by CMake's `add_test` for no builds on machines without the CUDA Toolkit?

**Comment by Jacobfaib** [comment]
> What functionality of rapids_test are you looking for that isn't provided by CMake's add_test for no builds on machines without the CUDA Toolkit?

`rapids_test_install_relocatable()`. Specifically, our CI requires us to build tests/executables on one runner, then execute on another runner. We could not easily make this work using default CMake machinery.

I am sure it can be done (case in point, `rapids_test_install_relocatable()`), but `rapids_test()` ended up being the most ergonomic solution.

**Comment by robertmaynard** [comment]
@Jacobfaib Does https://github.com/rapidsai/rapids-cmake/pull/480 resolve this issue for you
