### ISSUE TITLE
Broken links in "Usage" section

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rapids-cmake#489]
On [this rapids-cmake doc page]( https://docs.rapids.ai/api/rapids-cmake/stable/basics/#usage ), am seeing the following links:

<img width="863" alt="Screenshot 2023-11-15 at 1 41 29 PM" src="https://github.com/rapidsai/rapids-cmake/assets/3019665/4937dfae-e1cf-4655-bca4-12d2b16ef38b">

Clicking on each of these leads to "Page Not Found"

<hr>

Looking at the relevant Rst, see the following

https://github.com/rapidsai/rapids-cmake/blob/6f1ce07e13007a5629d726a13688f5adade2084b/docs/basics.rst?plain=1#L34-L40

IIUC these are meant to point to subsections in this file

https://github.com/rapidsai/rapids-cmake/blob/6f1ce07e13007a5629d726a13688f5adade2084b/docs/api.rst?plain=1#L1

**Comment by robertmaynard** [comment]
The transformation from rst to html seems to be different now. Previously we would generate `/rapids-cmake/basics.html` and `/rapids-cmake/api.html` but now we generate `rapids-cmake/basics/index.html` and `rapids-cmake/api/index.html` which causes the relative links to break.

**Comment by bdice** [comment]
Solved by #509.

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

Do the docs need to rebuild before this change shows up?

**Comment by bdice** [comment]
Yes, probably. I'd give it a day or so.
