### ISSUE TITLE
[BUG] Exported cmake files are in `lib64` instead of `lib`

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/rapids-cmake#56]
**Describe the bug**
In at least the librmm and libcudf 21.08 packages the cmake config and target files are in the `lib64/cmake` folder whereas they were previously in the `lib/cmake` folder.  This differs from all other conda packages which also use the `lib/cmake` folder. I also believe it breaks `find_package` searches from working as expected.

**Steps/Code to reproduce bug**
See packages here: https://anaconda.org/rapidsai/librmm/files?version=21.08.00

**Expected behavior**
CMake config and target files should be in `lib/cmake`

**Comment by kkraus14** [comment]
Note in running builds / installs locally it properly places them into `lib/cmake`  so this may be an issue in how the commands are being invoked as opposed to in `rapids-cmake`. cc @raydouglass

**Comment by robertmaynard** [comment]
> Note in running builds / installs locally it properly places them into lib/cmake
By locally do you mean bare metal or from inside a conda env?

**Comment by robertmaynard** [comment]
Background:
Rapids-cmake defers the computation of the install location to CMake's GNUInstallDirs module. That module will select `lib64` when it detects it is on a 64bit Linux Distro that isn't Debain. Alpine, or Arch based.

**Comment by kkraus14** [comment]
Aha, I was doing it in on an Ubuntu machine in a Conda environment. Sounds like our build process uses CentOS nowadays and so it places it in `${CMAKE_INSTALL_PREFIX}/lib64` instead of the expected `${CMAKE_INSTALL_PREFIX}/lib` in conda packages.

**Comment by kkraus14** [comment]
Fixed by #57

**Comment by raydouglass** [comment]
FYI, this affected multiple libraries:
- librmm
- libcudf
- libcuml
- libcugraph
- libcuspatial
