### ISSUE TITLE
[FEA] Allow providing a different default `versions.json`

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/rapids-cmake#587]
**Is your feature request related to a problem? Please describe.**
Need the ability to specify the default `versions.json` file used by a build, rather than always using the one in rapids-cmake.

**Describe the solution you'd like**
* Support `rapids_cpm_init(DEFAULT_VERSION_FILE <file>)`
* Support `-DRAPIDS_CMAKE_CPM_DEFAULT_FILE=<file>`

**Describe alternatives you've considered**
Right now we have to fork rapids-cmake, modify `versions.json`, and configure each project with custom `-Drapids-cmake-repo=` and `-Drapids-cmake-branch=` arguments.

**Additional context**
This is necessary for doing CCCL upgrades, modifying versions of dependencies built in DLFW, etc.

**Comment by robertmaynard** [comment]
We should do this feature and https://github.com/rapidsai/rapids-cmake/issues/552 at the same time so we have symmetry

**Comment by vyasr** [comment]
Could you remind me why using an override json isn't sufficient here?

**Comment by robertmaynard** [comment]
Closing as this feature is now complete with #596 being merged.
