### ISSUE TITLE
will you move libcudacxx to cccl in versions.json? [BUG]

### ISSUE THREAD

**Issue by idealboy** [rapidsai/rapids-cmake#598]
**Describe the bug**

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - CMake version

**Additional context**
For harder to track issue it can be helpful to attach the file generated from `cmake --system-information <file>` when executed from the same environment as the failure.

**Comment by vyasr** [comment]
Could you clarify what you are asking? [CCCL is already in versions.json](https://github.com/rapidsai/rapids-cmake/blob/branch-24.06/rapids-cmake/cpm/versions.json#L8), but we have libcudacxx as well for legacy support. We will eventually remove libcudacxx.

**Comment by vyasr** [comment]
I'm going to close this issue as I think the question has been answered, but feel free to reopen if there is more to say here.
