### ISSUE TITLE
[BUG] `rapids_test_install_relocatable()` does not play nice with `gtest_discover_tests(DISCOVERY_MODE PRE_TEST)`

### ISSUE THREAD

**Issue by Jacobfaib** [rapidsai/rapids-cmake#690]
Full description of the bug can be found here: https://gitlab.kitware.com/cmake/cmake/-/issues/26294 (specifically https://gitlab.kitware.com/cmake/cmake/-/issues/26294#note_1568638)...

...but the TL;DR is that the `CTestInstall.cmake` rewriting done by `rapids_test_install_relocatable()` eventually leads to `include()`-ing `GoogleTestAddTests.cmake`. This module -- if called in scripting mode (which it will be at install-time) -- will attempt to call a function which expects certain variables to be predefined. These variables are not defined, and hence install errors out.

**Comment by robertmaynard** [comment]
`rapids_test_install_relocatable` only supports installing and running tests added by `rapids_test_add`. You can't install tests added via `gtest_discover_tests` as those aren't known when the install step is run.

We should be able to update `rapids_test_install_relocatable` to work around the issue of mixing `gtest_discover_tests` and rapids-cmake tests, but your installed test set will not include any of the tests found by `gtest_discover_tests`
